### ISSUE TITLE
Bug when clicking on the PulseTile home button 

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#10]
When you click on the PulseTile home button, it should take you back to the Business Intelligence (charting) view, however instead it takes you to the all patient Multi Patient View.

**Comment by dkryvosheya** [comment]
@tony-shannon regarding this issue - if we change link on the logo, how would user will be able to view all patients within the application? I guess, we need to have some kind of link to non-filtered patient list - what's your suggestions, Tony?

**Comment by PhilBarrett** [comment]
Hi @dkryvosheya - happy to remove that function to be able to see all patients at the MPV.

**Comment by dkryvosheya** [comment]
Hi, @PhilBarrett - can you please clarify - I'm not sure I understood you correctly here - so, we're removing the link to the MPV from the application logo - that's OK, but how would MD get to the MPV (without clicking on the graph - it's giving limited amount of patients based on which graph was clicked).

**Comment by tony-shannon** [comment]
Can you give some explanation before closing please?
thanks
T

**Comment by dkryvosheya** [comment]
Sure - so, we've adjusted the link on the logo to send user to application's title screen (in this case it's graphs page) - for the reason if user would like to get to his homepage quickly, without modifying URL of the page - it's used as a common practice across the web.

**Comment by tony-shannon** [comment]
thanks Dmitry
