### ISSUE TITLE
Advanced Search - Age Range Timeline 

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#11]
The timeline within Advanced Search is compressed (see screenshot) so you can't see any of the numbers or the scaling. If you click on it, it expands, but should spread out from the outset.

![screenshot 2017-06-08 at 09 29 55](https://user-images.githubusercontent.com/12699244/26919299-26e5e56a-4c2d-11e7-9f4f-c6739f4c765a.png)

**Comment by dkryvosheya** [comment]
What browser did you used, Phil? 
If it's Google Chrome - which version you're using currently (and can you reproduce the issue now on http://dev1.ripple.foundation)? Thanks!

**Comment by dkryvosheya** [comment]
I'm not able to reproduce the issue - it could been coming as our QA feedback, I need to check - seems to be already patched

**Comment by tony-shannon** [comment]
![image](https://user-images.githubusercontent.com/939996/27186028-0e9dff30-51df-11e7-9989-7be8722e87e6.png)
Still not working , can you please try this functionality out and ensure its all working ok?
thanks, Tony

**Comment by dkryvosheya** [comment]
@tony-shannon I'm not sure as well here if Rob already serves it over the middleware - I know that Ian already implemented this on his end. I'll check with Rob tomorrow as well

**Comment by tony-shannon** [comment]
Please do
thanks
Tony

**Comment by tony-shannon** [comment]
just d/w Rob
He is awaiting 2 more fixes to the Advanced Search UI
1) send the min and max age values in the request
2) allow for text entry as well as widget entry (Dmitry, please let me know what you can easily do on this)

@dkryvosheya can you confirm your actioning those please?

thanks
T

**Comment by dkryvosheya** [comment]
As per item #2 - there is no need for us to do that, in my opinion - the plugin we're using to show the datepicker allows us to do the following: 
1. Click on the month gives year view: http://prntscr.com/fo970o -> http://prntscr.com/fo97da
2. When repeated, month are switched to years: http://prntscr.com/fo97da -> http://prntscr.com/fo97mp; 

In my opinion, this is fine for user to go to, for example, 1989 in a couple of clicks; 
What do you think?

**Comment by tony-shannon** [comment]
thanks @dkryvosheya 
Agree the datepicker is excellent, but users do like to use keyboard for direct entry eg 26/06/2017
.. would that be a problem to enable as an option?
thanks

**Comment by dkryvosheya** [comment]
@tony-shannon do you mean something like this? 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

Please note, that this solution have limited browser support: http://caniuse.com/#search=type%3D%22date%22

Should we switch our datepicker with this native one?

**Comment by tony-shannon** [comment]
which datepicker are you using please put link here so we can compare
thanks
T

**Comment by dkryvosheya** [comment]
We're currently using this one: https://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by tony-shannon** [comment]
OK looks like this will allow some editing inline, so should allow for "text entry as well as widget entry"
Can you check it out please?
BTW the format to display dates should be 
12/06/1970 is 12 June 1970
Can it handle that?

**Comment by dkryvosheya** [comment]
Yes, but only using third-party libraries (using moment.js in this case) - http://jsfiddle.net/g7mvaosL/

Should we aim for that @tony-shannon ?

**Comment by tony-shannon** [comment]
If you can combine that third party moment.js with the bootstrap-datetimepicker/ then perhaps its the best blend? 
Hope I've understood properly
thanks
T

**Comment by tony-shannon** [comment]
testing task list
- [ ] a task list item
- [ ] list task #2

**Comment by dkryvosheya** [comment]
Updated on dev1.ripple.foundation

**Comment by tony-shannon** [comment]
works well , thanks
