### ISSUE TITLE
Advanced Search - unable to clear previous search to search again

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#12]
Within advanced search, if you search for 9999999000 it returns Ivor Cox's record as expected. If you go back in to advanced search and search for a new record (e.g. 9999999001) it doesn't action the request or there is no option to clear and start again. 

Same behaviour when searching by surname & firstname

**Comment by dkryvosheya** [comment]
Patched it up on http://dev1.ripple.foundation/
