### ISSUE TITLE
Clinical querying is not hooked up

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#13]
Unable to perform clinical queries within the platform

**Comment by dkryvosheya** [comment]
Duplicated within QEWD repository;

**Comment by tony-shannon** [comment]
Sorry Dmitry, you need to provide the link to the related QEWD repo here before closing it.
thanks
Tony

**Comment by dkryvosheya** [comment]
Link to QEWD issue: https://github.com/RippleOSI/Ripple-Qewd/issues/32
QEWD - Clinical Queries not hooked up
