### ISSUE TITLE
Unable to view images

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#14]
Orthanc does not appear to be hooked up to the demonstrator

![screenshot 2017-06-08 at 09 41 43](https://user-images.githubusercontent.com/12699244/26919774-b6115732-4c2e-11e7-916e-b6587180b103.png)

**Comment by dkryvosheya** [comment]
Issue is non-present on http://dev1.ripple.foundation/, the images are viewable
