### ISSUE TITLE
Left hand menu headers ux enhancement

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#16]
Depending on your screen size/resolution the full left hand menu doesn't fit on a single screen. There is nothing to show that there are more menu items to view in this scenario, preventing the user having a full picture of the patient (see screenshots)

![screenshot 2017-06-08 at 09 45 13](https://user-images.githubusercontent.com/12699244/26919919-3c4b5514-4c2f-11e7-8bff-89df6dab2985.png)

![screenshot 2017-06-08 at 09 45 28](https://user-images.githubusercontent.com/12699244/26919917-3c1e0640-4c2f-11e7-81c9-a038a6dbed4b.png)

**Comment by dkryvosheya** [comment]
@PhilBarrett @tony-shannon some suggestions - we can, for example, reduce spacing between the items (this way we would be able to display more elements)
Or, on the other hand - some kind of 'v' symbol is possible as well to show user that there is some items below the default page render; 
Or, the most simple solution here will be addition of the scrollbar to the menu section; 

What's your thoughts, Tony?

**Comment by PhilBarrett** [comment]
@simongamester I believe has been thinking about this too. He might have a view too.

**Comment by simongamester** [comment]
Yes, we've discussed this before. Would suggest adding a native scrollbar to the side nav, only visible when the height of the side bar is greater than the window. Would this not just be an overflow-y: scroll? 

This slide in menu seems to do this:
http://callmenick.com/_development/slide-push-menus/

If the browser window is too narrow, scroll bars are automatically added:
![screen shot 2017-06-13 at 16 14 13](https://user-images.githubusercontent.com/8059219/27089802-6111e7b4-5053-11e7-941e-bdc6ac06b1af.png)

I like that they've added a 30px divider to the right of the menu, which is replaced by scrollbars when needed. Keeps the layout consistent:
![screen shot 2017-06-13 at 16 15 15](https://user-images.githubusercontent.com/8059219/27089861-87747fca-5053-11e7-9af9-41a20a212805.png)

**Comment by tony-shannon** [comment]
Hi Dmitry
Happy to try Simons suggestions
thanks
T
