### ISSUE TITLE
Refreshing screen takes you back to the business intelligence landing screen

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#17]
When you click to refresh the content, it should bring you back to the patient and screen you were wishing to refresh, instead it takes you back to the landing screen at the business intelligence view.

**Comment by dkryvosheya** [comment]
It's the way the application middleware behaves, as far as I'm concerned - should be fixed on QEWD level

**Comment by dkryvosheya** [comment]
Moved over to QEWD repository;

**Comment by tony-shannon** [comment]
Where is the link to the QEWD related issue please?

**Comment by dkryvosheya** [comment]
@tony-shannon hi, should I link the corresponding QEWD issue as a comment? like, 
https://github.com/RippleOSI/Ripple-Qewd/issues/35 for current one?

**Comment by tony-shannon** [comment]
Yes, in the comment is fine.
Suggest you reference the issue name as well as the issue link as you have
done.
Thanks
T

**Comment by dkryvosheya** [comment]
Sure, Tony, will do.

**Comment by dkryvosheya** [comment]
Issue transferred to QEWD Repository: https://github.com/RippleOSI/Ripple-Qewd/issues/35
EQWD General - Browser refresh issue #35
