### ISSUE TITLE
TS feedback on 17/Jan/31 build

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#2]
Test Results  - empty columns ? backend issue

Procedures -  empty columns ? backend issue

Referrals - will need Request & Response splitting as per earlier Social Care demo work. 
see this video in full screen to see what was done there
https://youtu.be/NfgE3BUvQbY?t=157

MDT - Question & Discussion should be multiline boxes when editing

Images- need to hook in PACS Dicom server , need to add Pan function along with Zoom

Vitals - detail panel to rearrange order, will update on JIRA

General- After searching.. eg Pt Cox.. the breadcrumb trail remains the same, should it be cleared/refreshed?

**Comment by dkryvosheya** [comment]
All items within the list are now done;
