### ISSUE TITLE
Test Results - Data not being populated 

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#20]
Test Name, Status & Conclusion are not populating. 

![screenshot 2017-06-08 at 09 56 14](https://user-images.githubusercontent.com/12699244/26920412-e89333e0-4c30-11e7-89ed-9ea512a110aa.png)

![screenshot 2017-06-08 at 09 56 37](https://user-images.githubusercontent.com/12699244/26920418-ea964768-4c30-11e7-9e8f-4ca8b766a390.png)

**Comment by dkryvosheya** [comment]
Some data fields are coming empty indeed, while some do have an information: http://prntscr.com/fhc019

**Comment by tony-shannon** [comment]
Sorry Dmitry , if there are empty field are u saying its a QEWD related issue>?
If so please raise and issue there and post the link to the issue here
thanks, Tony

**Comment by dkryvosheya** [comment]
@tony-shannon, no, it's not QEWD-related, it's related to ethercis in this case - database doesn't contain the information for us to show, please check the screenshot attached: http://prntscr.com/fhc019

**Comment by tony-shannon** [comment]
Please raise as a QEWD Ripple related issue for now, can be sorted from
there
T

**Comment by dkryvosheya** [comment]
Duplicated within QEWD repository: https://github.com/RippleOSI/Ripple-Qewd/issues/38 
QEWD - Test Results - Data not being populated
