### ISSUE TITLE
Vital Signs - Date undefined error

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#21]
![screenshot 2017-06-08 at 09 59 08](https://user-images.githubusercontent.com/12699244/26920564-4d4c59e2-4c31-11e7-9410-7f85497defac.png)

See related pull requests for both front end and back end for QA review before accepting/rejecting

**Comment by dkryvosheya** [comment]
Patched;

**Comment by tony-shannon** [comment]
Can you confirm this is now working please?

**Comment by dkryvosheya** [comment]
Yes, It's up and running on http://dev1.ripple.foundation/
