### ISSUE TITLE
Clinical Statements - Not being stored

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#22]
After creating a new clinical statement it doesn't store the new entry (not a refresh issue).

**Comment by dkryvosheya** [comment]
http://prntscr.com/fhbywy - Clinical statement retuns an empty value from the middleware level for some reason, without an ability to create a statement as well (dropdowns which are populated from the source are empty as well - http://prntscr.com/fhbzj5)

**Comment by dkryvosheya** [comment]
Currently operational;
