### ISSUE TITLE
Events data not populating

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#23]
![screenshot 2017-06-08 at 10 15 16](https://user-images.githubusercontent.com/12699244/26921264-676f75f0-4c33-11e7-921b-d2b1a259330d.png)

Event name, date, Type, notes not populating

**Comment by dkryvosheya** [comment]
http://prntscr.com/fhbxvu - Event Name field (hosted as serviceTeam on the middleware level) is not being populated, when Event Type and Notes fields are missing on the middleware level.

**Comment by dkryvosheya** [comment]
Moved over to QEWD repo

**Comment by tony-shannon** [comment]
Please update this issue here accordingly with a link to the QEWD related issue before closing it

**Comment by dkryvosheya** [comment]
Duplicated within QEWD repository: https://github.com/RippleOSI/Ripple-Qewd/issues/33
QEWD - Events missing data

**Comment by tony-shannon** [comment]
@dkryvosheya can we get an update on the UI json required for read/writes here please
@robtweed is awaiting to be able to progress https://github.com/RippleOSI/Ripple-Qewd/issues/33

**Comment by dkryvosheya** [comment]
As discussed, this will be our task for Monday.

**Comment by dkryvosheya** [comment]
@tony-shannon Implemented the feature, tested webRTC - working as intended;
Please review;

**Comment by PhilBarrett** [comment]
Hi @dkryvosheya we went to test the feature out and it appears that when a new event is created, it generates two events, one which you can join, the other which you can't. Please can you investigate.

Event you can join
![screen shot 2017-07-25 at 17 43 22](https://user-images.githubusercontent.com/12699244/28585022-d0e6b2e8-7166-11e7-9916-134a04522476.png)

Duplicated event, which you can't join
![screen shot 2017-07-25 at 17 43 33](https://user-images.githubusercontent.com/12699244/28585021-d0de7e70-7166-11e7-95ad-14eddff79c44.png)

**Comment by dkryvosheya** [comment]
Investigated this issue, @PhilBarrett @tony-shannon - it's more QEWD issue, other than UI. Duplicated over @QEWD repository - https://github.com/RippleOSI/Ripple-Qewd/issues/49

**Comment by robtweed** [comment]
Duplicate event posting should now be working properly

**Comment by robtweed** [comment]
Just re-read my last comment - I mean that duplicates should no longer be being posted, and the problem has been fixed

**Comment by PhilBarrett** [comment]
Tested and working fine, thanks @robtweed

**Comment by thanh121094** [comment]
Hi @dkryvosheya, @PhilBarrett  , I seen that you tested and working fine the Events features. However, I am using Ubuntu 16.04 64-bit machine, npm version 3.10.10, node version 6.11.4. I have some problems.

**1. It appears like that image:**
![screen](https://user-images.githubusercontent.com/24429197/31986787-f468d49c-b993-11e7-8e77-5ebc59df3588.png)

The console log displays:

`angular.js:13920 TypeError: Cannot read property 'value' of undefined
    at EventsListController.setCurrentPageData (http://localhost:9000/index.js?9e4f4bf4bfcd43a37b56:148310:106)
    at http://localhost:9000/index.js?9e4f4bf4bfcd43a37b56:148417:28
    at getStateSlice (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:60331:16)
    at Object.connect (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:60299:18)
    at EventsListController (http://localhost:9000/index.js?9e4f4bf4bfcd43a37b56:148415:31)
    at Object.invoke (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:13925:20)
    at $controllerInit (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:19561:35)
    at nodeLinkFn (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:18470:35)
    at compositeLinkFn (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:17827:14)
    at publicLinkFn (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:17707:31) <div class="section-main ng-scope" ui-view="main" data-ng-animate="1">`

2 . I've tried to comment the value which of undefined in the events-list.component.js file. And it's not displays console log error but It's also not displays any data. Furthermore, When I choose appointment, admission, transfer in the create button. The console log displays:

`angular.js:13920 
Rejection {$id: 0, type: 6, message: "The transition errored", detail: TypeError: Cannot read property 'state' of undefined at Transition.addResolvable (http://localho…}
$id
:
0
detail
:
TypeError: Cannot read property 'state' of undefined at Transition.addResolvable (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:2261:65) at http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:6179:16 at Array.forEach (<anonymous>) at addCoreResolvables (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:6178:23) at invokeCallback (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:2916:35) at TransitionHook.invokeHook (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:2928:27) at Function.TransitionHook.invokeHooks (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:3037:42) at new Transition (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:2040:42) at TransitionService.create (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:6061:17) at StateService.transitionTo (http://localhost:9000/vendor.js?9e4f4bf4bfcd43a37b56:5714:57)
message
:
"The transition errored"
type
:
6
__proto__
:
toPromise
:
ƒ ()
toString
:
ƒ ()
constructor
:
ƒ Rejection(type, message, detail)
__proto__
:
Object`

When I clicked discharge button, it displayed like that: 
![aaaa](https://user-images.githubusercontent.com/24429197/31987181-30ff1cee-b995-11e7-8087-9070b0891ddb.png)

Do you have ideas to fix this issues? 

Thanks,
Thanh from ThinkLabs VN
