### ISSUE TITLE
Theming improvements please

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#25]
![image](https://user-images.githubusercontent.com/939996/27186345-f73499c0-51df-11e7-87bc-08b6ba447014.png)
![image](https://user-images.githubusercontent.com/939996/27186361-091efb3a-51e0-11e7-9797-6036e2ba6dfa.png)
these are the areas that would like configurable in the first instance please

Phil will the 2 colours schemes he likes here shortly

**Comment by PhilBarrett** [comment]
![screenshot 2017-06-15 at 15 40 24](https://user-images.githubusercontent.com/12699244/27186709-0da900b4-51e1-11e7-8431-31b429fec6c2.png)

![screenshot 2017-06-15 at 15 40 07](https://user-images.githubusercontent.com/12699244/27186708-0da7dcca-51e1-11e7-9c9b-4ef55d0d3b5a.png)

**Comment by tony-shannon** [comment]
So I would like 3 options please
Green, Grey & Purple
Is that ok/clear?
thanks
Tony

**Comment by dkryvosheya** [comment]
Updated http://dev1.ripple.foundation/ with the changes.

**Comment by PhilBarrett** [comment]
Looks good @dkryvosheya , thank you. Good to see the palate applied across
the platform too, rather than just the header.

**Comment by tony-shannon** [comment]
Would you mind testing this Phil,
inc Application Name and Logo change?
thanks
T
