### ISSUE TITLE
HTTPS: After logging in, the user should arrive at the page he has been requesting earlier

### ISSUE THREAD

**Issue by dkryvosheya** [PulseTile/PulseTile#27]
After Auth0 logging in user should be sent to requested earlier page by URL

**Comment by dkryvosheya** [comment]
Updated https://dev1.ripple.foundation/#/patients/9999999000/medications

**Comment by tony-shannon** [comment]
Great well done

If you look closely at the browser behaviour you'll see it flicks through
this view before landing on the auth0 login page and the new theme below etc
Can we explain & amend this please?
A simple "loading page" message would be better.

[image: Inline images 1]


[image: Inline images 2]

thanks
Tony

**Comment by dkryvosheya** [comment]
We'll investigate this behavior, Tony.

**Comment by tony-shannon** [comment]
thank you
T

**Comment by dkryvosheya** [comment]
Excluding script from <head> did not help, so we added a loading spinner to hide the flashing of the application before the auth dialog appears.
