### ISSUE TITLE
Introduce the ordering of the menu items

### ISSUE THREAD

**Issue by dkryvosheya** [PulseTile/PulseTile#28]

**Comment by tony-shannon** [comment]
Lets go with this order please;

Patient Summary
Problems/Diagnosis
Medications
Allergies
Contacts

Events
Documents

Orders
Test Results
Procedures

Clinical Notes
Clinical Statements
Personal Notes

Vaccinations
Vital Signs

Images 
Drawings

Referrals
MDT
Transfer of Care

**Comment by tony-shannon** [comment]
Can you give an update before closing please?
T
