### ISSUE TITLE
Click on date-time should link across to the corresponding heading

### ISSUE THREAD

**Issue by dkryvosheya** [PulseTile/PulseTile#29]
i.e. click on vitals date should go to vitals

**Comment by tony-shannon** [comment]
Wonderful progress, many thanks!

A small issue to troubleshoot please

See here : Diagnosis count of 2
![image](https://user-images.githubusercontent.com/939996/27444463-5e882428-576e-11e7-9f9d-8ab94659d5b1.png)

Click through shows 7 Diagnosis in the table;
![image](https://user-images.githubusercontent.com/939996/27444513-7dc9cf76-576e-11e7-9eeb-c113dc689690.png)

Can you investigate please

**Comment by dkryvosheya** [comment]
Hi, @tony-shannon - we're getting this number from the middleware - http://prntscr.com/fn5djy - should I hit up Rob to investigate on his end?

**Comment by tony-shannon** [comment]
Yes please do
thanks
T

**Comment by tony-shannon** [comment]
can you please also check why numbers with decimal points are here please?
![image](https://user-images.githubusercontent.com/939996/27483099-f55e1030-581b-11e7-9437-2f5c1f3c3707.png)

**Comment by tony-shannon** [comment]
Id also let to set these settings up as default values on start up please
![image](https://user-images.githubusercontent.com/939996/27483256-891946a0-581c-11e7-84de-396d8664dc5e.png)

**Comment by dkryvosheya** [comment]
Re decimal: http://prntscr.com/fna1z1 - values are coming from the middleware as well in this case.

**Comment by tony-shannon** [comment]
thanks
Please pass this onto Rob as QEWD-Ripple issue then please, to resolve in
QEWD or EtherCIS layers
Tony

**Comment by dkryvosheya** [comment]
Passed over to middleware repository, https://github.com/RippleOSI/Ripple-Qewd/issues/41
