### ISSUE TITLE
branches need tidy up please

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#31]
see screenshot below
![image](https://user-images.githubusercontent.com/939996/27483012-8b8413bc-581b-11e7-8091-fecba9fea5c5.png)

**Comment by tony-shannon** [comment]
![image](https://user-images.githubusercontent.com/939996/27483000-7fc3ffb0-581b-11e7-89cd-cdef355dc66a.png)

**Comment by dkryvosheya** [comment]
Removed every branch (can't delete your patch, Tony, can you do it yourself?)

**Comment by tony-shannon** [comment]
Yes I've closed that patch branch, thanks
