### ISSUE TITLE
Connect clinical queries to API

### ISSUE THREAD

**Issue by dkryvosheya** [PulseTile/PulseTile#32]

**Comment by tony-shannon** [comment]
NB @dkryvosheya the behaviour expected here is that the result should populate a graph in the first instance, not the MPV
See this section of video to explain;
https://youtu.be/0kupZZH_S5E?t=114

So search for Patients + Diagnosis  + contains + Asthma would show graph by age.. then click on the bars to get the Search + Age Band in the MPV view

BTW Rob says he has updated you on the UI side of other fixes that need to be made.. are you clear what they are

**Comment by dkryvosheya** [comment]
Updated the UI on dev1.ripple.foundation according to the instructions above

**Comment by tony-shannon** [comment]
Great work , many thanks

Just a few bugs here to remedy

search query box should autocomplete "contains". its the only available value
browser title bar seems to say "Testing"?

Search results lose the detail of what the query was;
in both the search box and above the graph

![image](https://user-images.githubusercontent.com/939996/27747374-c49fc932-5dc2-11e7-8634-2c7442ab3f0f.png)

top left corner/Back button from the clinical query mpv brings you back to the start of the application, not the search chart result

Some patients dont have the right data.. maybe linked to QEWD or openEHR issue

**Comment by dkryvosheya** [comment]
All the feedback implemented on http(s)://dev1.ripple.foundation; @tony-shannon please close the ticket if everything is OK

**Comment by tony-shannon** [comment]
Seems to work great, many thanks!
