### ISSUE TITLE
Sign out button should delete cookies

### ISSUE THREAD

**Issue by dkryvosheya** [PulseTile/PulseTile#36]

**Comment by kbeloborodko** [comment]
Completed, @tony-shannon please check it

**Comment by dkryvosheya** [comment]
Investigating the use-case of the following:
I want to go straight to Events heading using the following url: https://dev1.ripple.foundation/#/patients/9999999000/events, after I log in as PHR user using google account I've been sent over back to the enter point of the application; 
Same behavior happens after I log in as IDCR user. 
We'll be on it as a top priority for now, @tony-shannon - I'll update you separately after the desired behavior is in place to check & close the ticket

**Comment by dkryvosheya** [comment]
We've applied necessary changes for sign-in and sign-out mechanisms, that take into accout the following: 
- Role of the user (PHR / IDCR)
- Requested page (app's home or particular heading / record) before the authentication using secure connection (HTTPS)
- User's ID (to avoid user with PHR role to sneak-peek into other's patients records accidentally or by purpose)

Please, check it out!

**Comment by dkryvosheya** [comment]
@tony-shannon should I close this issue? have you checked it?

**Comment by dkryvosheya** [comment]
We need to remove the /api/patients call while being logged in as a PHR user;

**Comment by dkryvosheya** [comment]
Updated and polished the functionality of login and logout; 
Please check @tony-shannon;

**Comment by PhilBarrett** [comment]
Thanks @dkryvosheya that's working fine now.
