### ISSUE TITLE
cant save Clinical Note: related to UI JSON

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#39]
FAO @dkryvosheya 

We have found that we cant save new Clinical Notes eg
![image](https://user-images.githubusercontent.com/939996/28925354-905bbffa-785c-11e7-9be9-a6c50880387d.png)

The problem has been traced as ;

the UI is sending it as a field named "notes" rather than "note"
here's what the UI sent
"body": {
        "clinicalNotesType": "Diabetic Clinic",
        "notes": "Type 2 Diabetes under reasonable control\nrecent weight loss\nsmoking still a problem\ntaking her meds\nno visual or foot problems reported",
        "dateCreated": "2017-08-03",
        "author": "bob.smith@gmail.com",
        "source": "openehr"
    },
so they need to change that field name to "note"  singular

**Comment by dkryvosheya** [comment]
Patched; 

Ready to be closed;

**Comment by dkryvosheya** [comment]
@tony-shannon @PhilBarrett this issue can be closed. have you had a time to check it out?

**Comment by PhilBarrett** [comment]
Working fine now, thanks Dmitry
