### ISSUE TITLE
cant add Referral - console error

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#40]
![image](https://user-images.githubusercontent.com/939996/28929323-9b84eca2-7867-11e7-89b1-70a8b6640f2b.png)

Please see error, cant add new referral

**Comment by dkryvosheya** [comment]
Patched, middleware issue blocks the record creation. 
Updated QEWD repo: https://github.com/RippleOSI/Ripple-Qewd/issues/51

**Comment by dkryvosheya** [comment]
@tony-shannon @PhilBarrett this issue can be closed. have you had a time to check it out?

**Comment by PhilBarrett** [comment]
Working fine, thanks Dmitry
