### ISSUE TITLE
Patient Lists - page filter shows list with one extra

### ISSUE THREAD

**Issue by linto17** [PulseTile/PulseTile#41]
In patient lists page showing a copy of the last one when doing filter, Please see the screenshot.
Thanks.
![screenshot from 2017-08-22 21-18-15](https://user-images.githubusercontent.com/23206794/29574760-1d2b4c7a-8780-11e7-96ae-42961f493f7a.png)

**Comment by dkryvosheya** [comment]
Hi, @linto17 - we spotted the issue, reason for this is that browser is not re-counting height of the tables, it happens after the browser's width is adjusted - let me take a look if we can force the height calculation after a symbol is added into the input. 

Thanks!

**Comment by linto17** [comment]
Thanks.

**Comment by anna-otrokhova** [comment]
@linto17 

This issue was fixed and  it can be checked here http://dev.ripple.foundation/#/charts 

(Please make sure that the version is Angular, in case it is React use this link for switching to Angular http://dev.ripple.foundation/api/ui/angular and do a hard reload in the browser )

**Comment by linto17** [comment]
Thanks.
