### ISSUE TITLE
Takes long time to open the application

### ISSUE THREAD

**Issue by linto17** [PulseTile/PulseTile#42]
The application is very slow to load for the first time.  http://showcase.ripple.foundation/

Can you please check this?

Thanks.

**Comment by tony-shannon** [comment]
thanks for flagging @linto17 

@kbeloborodko Kirill, can you please check out and benchmark please?

thanks
T

**Comment by kbeloborodko** [comment]
@linto17 hi! Thank you for the inquiry! Could you please provide more information about the problem you have experienced? How much time did it take to load the page? (it would be wonderful if you had an opportunity to make a video using some tool like jing, for example, so we can see what the issue is)

**Comment by linto17** [comment]
Hi, It took 2.38 minute to load. I have used incognito(chrome) to open the application. Application URL http://showcase.ripple.foundation/ there is no console logs in chrome developer console while loading.

**Comment by tony-shannon** [comment]
@kbeloborodko Do you need more info to reply to this ?

**Comment by anna-otrokhova** [comment]
@linto17 @tony-shannon

I am sorry for the late reply. 
We have tested it several times using incognito(chrome), hard reload and the result is usually about 17 seconds to load the site for the first time.

http://joxi.ru/12M7nQ7sMYZNJr
http://joxi.ru/p276jL6FoRG47m

Could you check it one more time, please?
In case you still have the same issue could you record console logs?

Also, it can be useful to check traceroute command to showcase.ripple.foundation and internet connection as well, just to exclude these reasons.

**Comment by linto17** [comment]
Thanks.
