### ISSUE TITLE
enable swap UI from Angular to React for Ripple showcase stack demo purposes

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#46]

**Comment by anna-otrokhova** [comment]
I have tested the swapping from React to Angular and from Angular to React version. Both cases are successful:
http://prntscr.com/h0usfb
http://prntscr.com/h0vi6h

**Comment by anna-otrokhova** [comment]
@tony-shannon 
 
Tony, can this issue be closed?

**Comment by tony-shannon** [comment]
Seems to be working very well.

Please add brief explanation as to how it works and the /paths needed to
make the swap here, for reference. Will need to add to pulsetile
Documentation in due course.

Once you've added explanation it can be closed.
Thanks
Tony

**Comment by anna-otrokhova** [comment]
Here are the steps for swapping between the versions:

Option 1
1) Follow the URL: 
http://dev.ripple.foundation/#/
2) Reload the page to get session token 
3) You can type this link right in the browser URL field :
3.1) For React version: http://dev.ripple.foundation/api/ui/react
3.2) For Angular version: http://dev.ripple.foundation/api/ui/angular
4) Do hard Reload of the page to get new information displayed

Option 2
You can do the same actions using any program (Postman f.e.) for API requests:

1) Follow the URL: 
http://dev.ripple.foundation/#/
2) Use this documentation http://dev.ripple.foundation/swagger-ui/dist/index.html for using right API requests.
2.1) GET /api/initialise (then use the token that is returned as the value of the Authorization header) 
2.2) GET /api/ui/{type}     eg GET /api/ui/react    or GET /api/ui/angular
http://prntscr.com/h2ny14

 What the API will do is to copy everything that is in the ~/ui-dist/{type} directory into the ~/qewd/www directory   - so you need to make sure that your latest React code is in ~/ui-dist/react   and that the latest working version of the Angular version is in ~/ui-dist/angular

**Comment by tony-shannon** [comment]
excellent , many thanks @anna-otrokhova
