### ISSUE TITLE
Add processing of PUT request for Allergies Heading

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile#48]
Add processing of PUT request for Allergies Heading

This issue may be linked to the existing ones: https://github.com/RippleOSI/Ripple-Qewd/issues/39
https://github.com/PulseTile/PulseTile-React/issues/44

**Comment by tony-shannon** [comment]
this is linked to this near duplicate issue in this repo
https://github.com/PulseTile/PulseTile-React/issues/44

**Comment by tony-shannon** [comment]
this may need to be reopened here too, +/- further dev work done on this codebase, it will need retesting anyway.
Its also linked to this issue in Ripple-Qewd https://github.com/RippleOSI/Ripple-Qewd/issues/39
