### ISSUE TITLE
"No [Heading eg Allergies/Medications/Orders etc]  - showing up for microseconds on loading patient headings, needs to say "Loading..."

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#49]
this issue can be seen as a widespread issue on navigating around a patient record before its cached locally
The Table shows "No Allergies" etc etc for a microsecond while the server fetches it then is over written
Its hard to screenshot so Ive taken this as the best way to explain it.. though its not the right patient to demo it
See the Type column in the Table here which says No Clinical Notes in this case
![image](https://user-images.githubusercontent.com/939996/31769131-2e9ed4fa-b4ca-11e7-8431-b5dbb5b6ad40.png)
This is what to watch out for when exploring the demo, that text needs updating/removing  

@kbeloborodko @anna-otrokhova

**Comment by anna-otrokhova** [comment]
@tony-shannon 
This issue was fixed and  it can be checked here http://dev.ripple.foundation/#/charts 

(Please make sure that the version is Angular, in case it is React use this link for switching to Angular http://dev.ripple.foundation/api/ui/angular and do a hard reload in the browser )

**Comment by tony-shannon** [comment]
looks very good @anna-otrokhova , I noted "Loading" in all headings except for Events, can you double check this please

great job on the ui swapperover api in QEWD-Ripple @robtweed

**Comment by anna-otrokhova** [comment]
@tony-shannon 

I got your point. Let us check and fix it.

**Comment by anna-otrokhova** [comment]
@tony-shannon 

Tony, this issue was fixed. Please check when you have time and let us know.

**Comment by PhilBarrett** [comment]
@tony-shannon @anna-otrokhova I've had a check of this now, working fine aside from events.

What was the fix applied please / cause?

**Comment by anna-otrokhova** [comment]
@tony-shannon 

<<I noted "Loading" in all headings except for Events, can you double check this please>>

Now "Loading" is present in Events tab as well.

**Comment by tony-shannon** [comment]
thanks @anna-otrokhova Yes this is fixed on dev, so I'll close this and you can update Showcase

**Comment by anna-otrokhova** [comment]
@tony-shannon 
We have updated showcase. So it works on showcase as well.

**Comment by tony-shannon** [comment]
Thanks Anna
