### ISSUE TITLE
Do you have any plan to support multiple languages?

### ISSUE THREAD

**Issue by ZuzooVn** [PulseTile/PulseTile#5]
Hi Guys
Do you have any plan to support multiple languages?
I think you should use i18next (http://i18next.com/) library for translation.

Best Regards,

Nam Vu

**Comment by tony-shannon** [comment]
Good idea certainly.

@kbeloborodko can you comment on if/how we could look at this at some stage please?

thanks
Tony

**Comment by kbeloborodko** [comment]
Sure, @tony-shannon.
Hi, @ZuzooVn, yes, most likely we will be using i18n plugin to implement multiple languages on the client-side level

**Comment by tony-shannon** [comment]
thanks @kbeloborodko 
Can we get an estimate of effort involved please?
eg French or whatever, assume once you plug it in switching the languages is easy
thanks
Tony

**Comment by kbeloborodko** [comment]
@tony-shannon given it another thought, this will require backend changes too in order to make the server data in different languages. For the frontend part ballpark estimate is 2 days to set up the core for the i18n integration and an average of 2-3 hours for each of the modules to integrate

**Comment by tony-shannon** [comment]
thanks @kbeloborodko 
FYI @ZuzooVn 
Not on our immediate to do list, but feel free to fork and submit a related pull request!
thanks
Tony
