### ISSUE TITLE
Incorrect displaying of data in Events tab -> Timelines

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile#51]
the issue with date displaying ( Events -> Timelines ) 
http://prntscr.com/h28pw4

Change the format of date from "1452595820958" to  "2010-05-14T00:00:00+02:00"

**Comment by tony-shannon** [comment]
thanks @anna-otrokhova 
Do we know if the fix is needed on the UI or Middleware side?

**Comment by anna-otrokhova** [comment]
@tony-shannon 

I am not sure about it. I think I will have the more particular information when our guys will start fixing it. 
But if we need some help from back end side  I will let you know and create the issue on QWED board. Am I right?

**Comment by tony-shannon** [comment]
" if we need some help from back end side I will let you know and create the issue on QWED board. Am I right?"  
--> Perfect, thanks Anna

**Comment by anna-otrokhova** [comment]
@tony-shannon 
 Tony, the issue was fixed here http://dev.ripple.foundation/
Could you check it please and let us know if we can transfer changes to http://showcase.ripple.foundation/#/charts  as well?

**Comment by tony-shannon** [comment]
yes @anna-otrokhova looks good to go to showcase, thanks

BTW we wont share our dev box details here, as that's for internal dev + testing, thanks

**Comment by anna-otrokhova** [comment]
@tony-shannon 

I am sorry for sharing the details. 
Ok. I will update you once it is done.

**Comment by tony-shannon** [comment]
No problem
thanks
T

**Comment by anna-otrokhova** [comment]
@tony-shannon 
The changes were successfully transferred to showcase machine as well.
