### ISSUE TITLE
Fix the issue with ui kit

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile#52]
1) The tabs are not clickable (while clicking there is no redirection to the needed place on the page)

**Comment by anna-otrokhova** [comment]
we have fixed the issue on ui-kit pages, now you can reach them here:

1) http://dev.ripple.foundation/#/ui-kit
2) http://showcase.ripple.foundation/#/ui-kit

**Comment by tony-shannon** [comment]
Sorry , what was the issue here?

**Comment by anna-otrokhova** [comment]
Before when user tried to click on any of the tabs user wasn't redirected to the needed place on page http://prntscr.com/h2nmpp
And after fixing when user clicks on any tab user is routed to the appropriate information 
http://prntscr.com/h2nr5k

**Comment by tony-shannon** [comment]
understood now, thanks,
