### ISSUE TITLE
Reduce build size to improve the situation with first loading on limited/slow bandwidth network

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile#53]
We are working on reducing the build size to improve the situation with charts loading on limited/slow bandwidth network

**Comment by anna-otrokhova** [comment]
@tony-shannon 

We have reduced the build size. Please check it and let us know the results (if the situation with first loading on limited bandwidth was improved) Thank you in advance.

**Comment by tony-shannon** [comment]
thanks
seems ok here , but I have good wifi and 3g , so not where I usually have
trouble.
Can I ask what reduction you've achieved?
Do you have a tool that simulates narrow bandwidth to test this yourselves?
thanks
Tony

**Comment by anna-otrokhova** [comment]
@tony-shannon 

<<Can I ask what reduction you've achieved?>>
We have reduced index.js file (6.8 MB -> 3.1 MB) and vendor.js file (2.5 MB -> 602 KB ) 

As result the pages load twice as fast as before .

<<Do you have a tool that simulates narrow bandwidth to test this yourselves?>> 
We have tested using dev console http://prntscr.com/h85yid , http://prntscr.com/h85ysy

My pleasure
Anna

**Comment by tony-shannon** [comment]
well done @anna-otrokhova 
that Chrome devtool is very helpful
I;ve tested with Slow 3g setting and seems to be ok.
Funnily if you test in offline mode, the spinner keeps spinning, can you take a look?

Will close this issue shortly..
T

**Comment by anna-otrokhova** [comment]
@tony-shannon 

Step 1) We send request to server and spinner starts spinning while waiting for the response
Step 2) Server sends response and the result is displayed on web interface

If you turn off the internet (offline mode) you can't get response so spinner will keep spinning

**Comment by tony-shannon** [comment]
OK, I'm not sure if this is sensible..
If we can work out that the browser is effectively offline, shouldnt it
pass back a message to say your internet connectivity is the problem?
Otherwise I/others will wait for the spinner, indefinitely....
Thanks

**Comment by anna-otrokhova** [comment]
@tony-shannon 

Dear Tony, 
Let me put it another way, please:
1) First case
Your internet is off from the start and you try to open the site  
You will get such results: http://prntscr.com/h8a7zv 
Site loading won't be even started. 

2) Second case
Step 1) We send request to server and spinner starts spinning while waiting for the response
Step 2) Server sends response and the result is displayed on web interface

You had internet from the start (on Step 1)
and internet was turned off between Step 1 and Step 2
http://prntscr.com/h8aa7x

So request was sent when you still had internet but response can't be sent back.
So you will see the error that internet connection is closed in dev console.

**Comment by tony-shannon** [comment]
thanks Anna
T

**Comment by kbeloborodko** [comment]
@tony-shannon 
1) First case
If we need to support offline mode for the entire PulseTile application we can use one of the existing solutions (for example, https://www.npmjs.com/package/angular-offline). Though this would mean, that we need to dig into the respective modules deeper, implement caching and offline behavior for all of the network communication functionality and test it. If you would like to go this way, I can try to come up with a ballpark estimate for this feature, but it would be an extensive task.

2) Second case
We can show an error to the user and hide the loader, if the connection was lost in between the request from the client and respective response from the server.

**Comment by tony-shannon** [comment]
thanks @kbeloborodko 

1) Good point, Offline working likely needs to be done at some point but not now, we can park that for now.

2) A well written error would be better, thanks

**Comment by anna-otrokhova** [comment]
@tony-shannon 


Dear, Tony!

I apologise for not getting back to you about your questions sooner.
We have discussed the range of options for a well written error. Here is the short list of possible solutions from our point of view:

1)  If connection was lost during initialising of the application a notification will appear instead of spinner sign: “Some connection error has occurred. Please check your connection and try again”  (For starting the application only)

2) If any server error 5xx returns from server we can display a note in popup window:
“Something is wrong with the server. Please try again later.”  ( For the whole site)

3) If 403 code is returned we can display a note in popup window:  “Your token has been expired. Please reload the page.” (For the whole site)

Just as example: http://prntscr.com/h9ylf2 , http://prntscr.com/h9yo0n 

Please let us know your feedback if our variants or some of them are preferable for you.

**Comment by tony-shannon** [comment]
HAppy to try those
thanks
T

**Comment by anna-otrokhova** [comment]
@tony-shannon 

Tony, our estimation for these tasks is 12 hours for each version (react and angular). We can include these tasks  into the schedule after finishing the current Block 2. 
What are your thoughts? 

Please let us know your feedback.

**Comment by tony-shannon** [comment]
Please email any estimates directly Anna, not a github discussion point

**Comment by anna-otrokhova** [comment]
@tony-shannon 
Ok, I am sorry.

**Comment by tony-shannon** [comment]
No prob
This issue can now be closed as we will open up issue for these other tasks,
thanks
