### ISSUE TITLE
Travis Build failing

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#55]
Hi @anna-otrokhova 
Can you take a look at this and let us know that needs to be done?
https://travis-ci.org/PulseTile/PulseTile/builds
thanks
Tony

**Comment by anna-otrokhova** [comment]
@tony-shannon 
Ok, Tony.
I will check it later.

**Comment by anna-otrokhova** [comment]
@tony-shannon 
Alexey has fixed this issue. Please check.

**Comment by tony-shannon** [comment]
thanks Anna, Alexey
