### ISSUE TITLE
install fails with module missing errors

### ISSUE THREAD

**Issue by pacharanero** [PulseTile/PulseTile#56]
I'm sure this is just going to be something silly I'm doing wrong (or not doing) but I'm getting a few errors when I try to build and run PulseTile locally, following the instructions here: https://github.com/PulseTile/PulseTile

`git clone` the repo
`cd /path/to/repo`
`npm install` completes with a couple of npm WARN only
`bower install` completes with a warning that we should start using Yarn :-) fair enough
`npm start` or `npm run build` both fail with errors:

```
ERROR in ./src/app/index.js
Module not found: Error: Cannot resolve module 'malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar' in /home/marcus/code/ripple/PulseTile/src/app
 @ ./src/app/index.js 43:0-65

ERROR in ./src/app/index.js
Module not found: Error: Cannot resolve module 'angularjs-slider' in /home/marcus/code/ripple/PulseTile/src/app
 @ ./src/app/index.js 33:0-27

ERROR in ./src/app/index.js
Module not found: Error: Cannot resolve module 'jquery-timepicker-jt' in /home/marcus/code/ripple/PulseTile/src/app
 @ ./src/app/index.js 47:0-31

ERROR in ./src/app/index.js
Module not found: Error: Cannot resolve module 'angular-jquery-timepicker' in /home/marcus/code/ripple/PulseTile/src/app
 @ ./src/app/index.js 49:0-36

ERROR in ./src/app/index.js
Module not found: Error: Cannot resolve module 'ng-scrollbars' in /home/marcus/code/ripple/PulseTile/src/app
 @ ./src/app/index.js 53:0-24

ERROR in ./src/app/index.js
Module not found: Error: Cannot resolve module 'angular-ui-select' in /home/marcus/code/ripple/PulseTile/src/app
 @ ./src/app/index.js 55:0-28

ERROR in ./src/app/index.js
Module not found: Error: Cannot resolve module 'angular-swiper' in /home/marcus/code/ripple/PulseTile/src/app
 @ ./src/app/index.js 57:0-25

ERROR in ./src/app/index.js
Module not found: Error: Cannot resolve module 'fabric.js' in /home/marcus/code/ripple/PulseTile/src/app
 @ ./src/app/index.js 63:0-20

ERROR in ./src/app/index.js
Module not found: Error: Cannot resolve module 'angular-bootstrap-datetimepicker' in /home/marcus/code/ripple/PulseTile/src/app
 @ ./src/app/index.js 65:0-43

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/app/scss/core.scss
Module build failed: 
@import '../../../bower_components/angular-bootstrap-datetimepicker/src/scss/datetimepicker';
^
      File to import not found or unreadable: ../../../bower_components/angular-bootstrap-datetimepicker/src/scss/datetimepicker
Parent style sheet: stdin
      in /home/marcus/code/ripple/PulseTile/src/app/scss/core.scss (line 20, column 1)
 @ ./src/app/scss/core.scss 4:14-169
```

Not sure where these libraries are supposed to be coming from?

I would have imagined all js dependencies get installed by npm?

**Comment by tony-shannon** [comment]
thanks Marcus, I'll add in prelim response from @kbeloborodko below, and lets continue this here;

_Thank you for providing the logs. They are very helpful. From what I can see you are missing bower dependencies as all of the errors that you get are based on the missing modules that are contained here https://github.com/PulseTile/PulseTile/blob/develop/bower.json. You mentioned that you executed bower install command successfully with a warning, but most likely corresponding bower components folder was not created for some reason. Could you please:

1) Clone a fresh copy of the repository

2) Run shell commands from the readme once again (npm install, bower install)

3) Make sure that bower install command succeeds and you have a bower_components folder in the root of the application that contains all of the modules that are part of the dependencies object in bower.json

4) Get back to me if that does not work, so we can think of the next steps_

**Comment by pacharanero** [comment]
Thanks @tony-shannon for posting @kbeloborodko's advice here

I've reinstalled everything as per that advice and it's working now. A n00b error somewhere along the line on my part I reckon.

Note that there were a number of deprecation warnings about (mainly) Angular packages that have now been renamed to the Angular.js namespace presumably to avoid clashing with Angular4 namespacing.

```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated ghooks@2.0.0: Use npmjs.com/husky instead, see https://github.com/gtramontina/ghooks/issues/166
npm WARN deprecated angular-ui-router@1.0.3: This npm package 'angular-ui-router' has been renamed to '@uirouter/angularjs'. Please update your package.json. See https://ui-router.github.io/blog/uirouter-scoped-packages/
npm WARN deprecated isparta-loader@2.0.0: Package is deprecated, use https://github.com/deepsweet/istanbul-instrumenter-loader
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli

> @uirouter/core@5.0.3 install /home/marcus/code/ripple/PulseTile/node_modules/@uirouter/core
> node ./migrate/migratewarn.js


> angular-ui-router@1.0.3 install /home/marcus/code/ripple/PulseTile/node_modules/angular-ui-router
> node migrate/migratewarn.js

WARNING! this npm package "angular-ui-router" has been renamed to "@uirouter/angularjs".  Please update your package.json
See https://ui-router.github.io/blog/uirouter-scoped-packages/ for details.
```

**Comment by tony-shannon** [comment]
thanks Marcus

Kirill , do u want to update naming of packages accordingly?

thanks
T

**Comment by kbeloborodko** [comment]
@tony-shannon package names are constantly changing and some versions become deprecated. I think it is a good idea to revisit our package.json once in a certain period of time (two-weeks or a month for example). We will add this task to our backlog with @anna-otrokhova

**Comment by tony-shannon** [comment]
Good idea
thanks Kirill
T

**Comment by anna-otrokhova** [comment]
@tony-shannon 
1) task was created https://github.com/PulseTile/PulseTile/issues/60 and added to the Angular board. 
2) May we close this issue now?

**Comment by anna-otrokhova** [comment]
I suppose it can be closed. As the issue was solved
