### ISSUE TITLE
WebRTC anomalies

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#6]
We've noticed a couple of anomalies with WebRTC on the current build. 

- When a clinician or patient joins an appointment it doesn't notify the other user in the chat pane (e.g. Dr  John Smith has joined chat, Dr John Smith has joined video (or vice versa) ). 
- The chat history isn't being stored within the appointment after the appointment ends. 
- SSL certificate required to remove warning notice

**Comment by tony-shannon** [comment]
thanks @PhilBarrett 
Can you add screenshots to help explain these issues..
thanks
T

**Comment by PhilBarrett** [comment]
@dkryvosheya do you have an update on this please?

**Comment by dkryvosheya** [comment]
@PhilBarrett @tony-shannon yes, I'm currently trying to determine what caused those issues after the migration from 138.68.134.7 machine, I'll update here when I find out what's the reason for that.

**Comment by dkryvosheya** [comment]
Patched chat history on dev1.ripple.foundation.

**Comment by tony-shannon** [comment]
Could you please retest and add screenshot of saved chat to prove fixed before closing

**Comment by dkryvosheya** [comment]
http://prntscr.com/fqzfec - here is the screenshot, Tony (don't forget to use secure version of the app, since non-secure version is not working properly with websockets)
