### ISSUE TITLE
Medication Heading - dev box > the information is not sent to web interface - invalid data

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile#68]
To check later.

showcase box:
Dose Timing is replaced with the data from Dose Amount field by POST request. 

Related issue: https://github.com/RippleOSI/Ripple-Qewd/issues/70

**Comment by anna-otrokhova** [comment]
The issue was fixed. There is still a minor issue on showcase box with Dose Timing fields.

**Comment by thangnguyen3si** [comment]
Hi @anna-otrokhova. I'm from Thinklabs VN. On the dev I've seen the problem resolved but the source code has no update. Can you support me about this issue

**Comment by anna-otrokhova** [comment]
@thangnguyen3si 
What do you mean by  "the source code has no update."
We didn't change anything on frontend side, the issue was fixed on back end side.

**Comment by thangnguyen3si** [comment]
@anna-otrokhova 
"the issue was fixed on back end side"
Can you send me commit id? i have problem with this issue in back end side?

**Comment by anna-otrokhova** [comment]
@robtweed 
Could you help please with this question?

**Comment by freshehr** [comment]
This appears to  ban issue with EtherCis which does not handle the AQL correctly - https://github.com/ethercis/ethercis/issues/95

**Comment by anna-otrokhova** [comment]
I will close this issue as it was solved on all machines.
