### ISSUE TITLE
Patient Summary empty on Startup

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#8]
On arrival to patient summary eg Ivor Cox the widgets are empty, until the Headings are explored  and then if you come back the Patient summary widgets have the data expected

**Comment by tony-shannon** [comment]
![image](https://user-images.githubusercontent.com/939996/26886325-f1a61d4c-4b9c-11e7-84f8-b378f8b4df45.png)
see example here

**Comment by dkryvosheya** [comment]
Already updated;
