### ISSUE TITLE
What is the plan for upgrade path to more recent Angular version?

### ISSUE THREAD

**Issue by pacharanero** [PulseTile/PulseTile#83]
Currently Pulsetile uses Angular 1.5.8.

From July 2018 Angular 1.x moves out of active development.
Angular 1.7.x will continue to receive Long Term Support (patches/security fixes) for 3 years

Therefore it would make sense to try to migrate to a more recent major Angular version (current stable branch is 6.1.0). Also the bulk of Angular devs will be familiar with more recent Angular versions, which have a more consistent, evolved and stable API, use the CLI tool, have a heavier influence of components, and do not pass $scope all over the place. 

What is the plan for upgrade path to more recent Angular?

**Comment by tony-shannon** [comment]
thanks for pointing that out  @pacharanero 
We are well aware.

PulseTile development began in 2014 and ran into 2015 when Angular 1.3 was the frontrunner, then the framework needed refactoring in Summer 2016 , which was done onto Angular 1.5 .
Angular 2 had just issued as 1st Release candidate in May 2016, was not final version til Sept 2016, so the advice we got at the time was to hold off on Angular 2 
https://en.wikipedia.org/wiki/Angular_(application_platform)#Version_2.0.0

Meanwhile React was on the rise at that time , so we took the decision sometime in 2017 to offer both AngularJS and ReactJS versions and our focus shifted to realising the [PulseTile-ReactJS ](https://github.com/PulseTile/PulseTile-React-Core) version.

About that time we started tracking Realworld.io, which is an amazing showcase of front and backend development frameworks
https://medium.com/@ericsimons/introducing-realworld-6016654d36b5
https://github.com/gothinkster/realworld
You will see that as of today that ReactJS remains the  No 1 choice FrontEnd framework there ( as it was from the start as I recall) so we have stuck with ReactJS as our recommended version for now.

We would love to be able to seed the development of more versions of PulseTile (if we had unlimited funds) , but also aware that offering PulseTile in the 16 frontend flavours on realworld would be unhelpful to the healthIT community tbh..

So for now we are focussed on supporting the frontrunning frontend framework, which is ReactJS

Coming back to Angular , we have an AngularJS version, we are open to migrating this Angular codebase to the latest version , now Angular (2,3,4,5) 6! and if someone wants that (eg if it becomes the most popular UI framework) and wants to fund that we will certainly be up for that, we just need a funded project to justify that (and tbh noone is asking for it at present, everyone we're talking to seems happy with ReactJS at present).

One other angle we are keeping an eye on is microfrontends, which is a very interesting idea to one to watch..
https://micro-frontends.org/
 
Hope that helps, Tony


Tony

**Comment by pacharanero** [comment]
Sounds good to me. React is much more lightweight and does not demand to own the whole page.

I think it would also be worth looking at [WebComponents](https://www.webcomponents.org/introduction) in the future as well.
